name: Deploy to GCP
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: 'id_token'
        workload_identity_provider: "projects/573882834568/locations/global/workloadIdentityPools/springboot-pool/providers/github"
        service_account: "springboot@springbootjava-459610.iam.gserviceaccount.com"

    





    
