name: GCP Auth via WIF

on: [push]

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Verify gcloud setup
      run: |
        gcloud --version
        gcloud auth list

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:

        token_format: "id_token"
        id_token_audience: "https://google.cloud" 
        workload_identity_provider: "container/container-453116/locations/global/workloadIdentityPools/practice-pool/providers/github-provider"
        service_account: "practice@container-453116.iam.gserviceaccount.com"

    - name: Print ID token (Debug)
      run: echo "ID Token: ${{ steps.auth.outputs.id_token }}"



    
